### ISSUE TITLE
Error when trying to use - issue with constructor

### ISSUE THREAD

**Issue by ndeblauw** [vemcogroup/laravel-smsapi#1]
I've installed the package in a Laravel 8 project. I'm trying to run the basic example, code below
```php
use Vemcogroup\SmsApi\SmsApi;

public function test()
{
  $to = '+3248684xxxx'; // commenting out last numbers for privacy
  $from = '+3249920yyyy';  // commenting out last numbers for privacy
  $message = 'This is a test message';

  SmsApi::send($to, $from, $message);
}
```
And this results in the following error:
```
Too few arguments to function Smsapi\Client\SmsapiHttpClient::__construct(), 0 passed in C:\project_path\\vendor\vemcogroup\laravel-smsapi\src\SmsApi.php on line 21 and exactly 3 expected
```

When I look at the code of the constructor in `SmsapiHttpClient`, it seems to me that you are trying to resolve the 3 parameters from the container, rather than that they need to be passed as parameters. But somehow this doesn't work.

Do I need to register somehow the `ClientInterface`,`RequestFactoryInterface` and/or `StreamFactoryInterface` in my project? If so, please could you explain where and how?

**Comment by danijelk** [comment]
@ndeblauw Hey Nico, didn't get a notification for this issue request.

So yea you are right, after they upgraded to v3 it seems like they changed their constructor and we didn't take account into that as we used their package in a different way.. To get you going this is what we are doing atm, we'll take a look at fixing the package once back from vacation so that it does something similar as to what we are doing with these 3 lines instead:
```
            $sms = SendSmsBag::withMessage($this->to, $this->text);
            $sms->from = $this->from;
            $sms->normalize = true;
            $service = (new SmsapiHttpClient())->smsapiComService(config('smsapi.token'));
            $sms = $service->smsFeature()->sendSms($sms);
```

**Comment by danijelk** [comment]
Could you check what version you are using, I have a hunch you are on v1 of the package?

**Comment by ndeblauw** [comment]
Hi @danijelk , thanks for coming back on this issue! When I couldn't get it to work, I actually wrote my own version of your SmsApi class, with only one difference: I included the curl httpclient and this was enough to get it working... See below.

![image](https://user-images.githubusercontent.com/4344869/125249572-a6e7b500-e2f5-11eb-8d0e-7b3963f12e9c.png)

**Comment by danijelk** [comment]
Indeed I saw it in our script as well now, didn't think of looking at that, update released thanks!
